services:
  api-service:
    build: . # Build from Dockerfile in current directory
    ports:
      - "9000:9000" # Mapping ports from our local machine to ports in the container
    environment:
      # Getting environment variables from .env file
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=db # DB Host is the name of the 'db' service below
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  mq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"   # For connection
      - "15672:15672" # For UI management

volumes:
  postgres_data: